wildfly/wildfly-server-migration

build/src/main/resources/config/environment.properties
https://issues.jboss.org/browse/CMTOOL-74 Remove comment about domain not being fully implemented from default configuration
=> CMTOOL-74: Remove comment about domain not being fully implemented from configuration

eap6-to-eap7/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_0UpdateUndertowSubsystem.java, eap6-to-eap7/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_1UpdateUndertowSubsystem.java, wildfly10/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/undertow/SetDefaultHttpListenerRedirectSocket.java
=> CMTOOL-123: fixes wfly 8 to eap 7 and wfly 10.1 update to undertow http listener

core/src/main/java/org/jboss/migration/core/env/SystemEnvironment.java, core/src/test/java/org/jboss/migration/core/env/AbstractEnvironmentTest.java, core/src/test/java/org/jboss/migration/core/env/MigrationEnvironmentTest.java, core/src/test/java/org/jboss/migration/core/env/SubEnvironmentTest.java, core/src/test/java/org/jboss/migration/core/env/SystemEnvironmentTest.java, core/src/test/java/org/jboss/migration/core/env/TaskEnvironmentTest.java, core/src/test/java/org/jboss/migration/core/ts/BasicMigrationTestCase.java, core/src/test/java/org/jboss/migration/core/ts/MigrationReportTest.java, core/src/test/java/org/jboss/migration/core/ts/MigrationTasksTest.java, core/src/test/java/org/jboss/migration/core/ts/TestServer.java, core/src/test/java/org/jboss/migration/core/ts/jboss/ConfigFilesDiscoveryTest.java, core/src/test/java/org/jboss/migration/core/ts/jboss/TestJBossServer.java
=> CMTOOL-126: QE core unit tests contribution

build/src/main/resources/configuration/environment.properties, eap7.0-feature-pack/src/main/resources/content/migration/configuration/environment.properties, eap7.1-feature-pack/src/main/resources/content/migration/configuration/environment.properties, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/MigrateDeploymentOverlays.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/MigrateDeployments.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/MigratePersistentDeployments.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/MigrateScannerDeployments.java, wildfly10.1-feature-pack/src/main/resources/content/migration/configuration/environment.properties
Reverts wildfly/wildfly-server-migration#86
=> Revert "CMTOOL-139: improve env configuration and user interaction options, t…"

eap7.1-feature-pack/src/main/resources/content/migration/README.md, wildfly10.1-feature-pack/src/main/resources/content/migration/README.md
Jira: https://issues.jboss.org/browse/JBEAP-12154
=> [JBEAP-12154] Fix the target server name in README.md

eap7.0-feature-pack/pom.xml, eap7.0-feature-pack/src/license/licenses.xsl, eap7.1-feature-pack/pom.xml, eap7.1-feature-pack/src/license/licenses.xsl, wildfly10.1-feature-pack/pom.xml
JBoss EAP related licensing fixes
=> JBEAP-13072, JBEAP-12878 

wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/MigrateScannerDeployments.java
Issue: https://issues.jboss.org/browse/CMTOOL-149
=> [CMTOOL-149] The tool goes on despite invalid input

cli/src/main/java/org/jboss/migration/cli/CommandLineConstants.java, cli/src/main/java/org/jboss/migration/cli/CommandLineOptions.java, cli/src/main/java/org/jboss/migration/cli/CommandLineServerMigration.java, cli/src/main/java/org/jboss/migration/cli/logger/CommandLineMigrationLogger.java, testsuite/integrated-server-migration-simple-test.sh, testsuite/integrated-server-migration-test.sh, testsuite/server-migration-simple-test.sh, testsuite/server-migration-test.sh
Issue: https://issues.jboss.org/browse/CMTOOL-150
=> [CMTOOL-150] Server migration tool accepts other values that it should

cli/src/main/java/org/jboss/migration/cli/CommandLineServerMigration.java
Issue: https://issues.jboss.org/browse/CMTOOL-162
Supersedes #116
=> CMTOOL-162: tool should not indicate abnormal termination on --help

docs/src/main/asciidoc/StandaloneDistribution-UserGuide.adoc, docs/src/main/asciidoc/topics/EAP6.4toEAP7.0-ServerMigration-ServerConfiguration-Subsystem-Update-ee.adoc, docs/src/main/asciidoc/topics/EAP6.4toEAP7.0-ServerMigration-ServerConfiguration-Subsystem-Update-remoting.adoc, docs/src/main/asciidoc/topics/IntegratedDistribution-ServerMigration.adoc, docs/src/main/asciidoc/topics/IntegratedDistribution-UserGuide.adoc, docs/src/main/asciidoc/topics/ServerMigration-ManagedDomain.adoc, docs/src/main/asciidoc/topics/ServerMigration-ServerConfiguration-MigrateReferencedModules.adoc, docs/src/main/asciidoc/topics/ServerMigration-ServerConfiguration-RemoveUnsecureInterface.adoc, docs/src/main/asciidoc/topics/ServerMigration-ServerConfiguration-Subsystem-Migrate.adoc, docs/src/main/asciidoc/topics/ServerMigration-StandaloneServer.adoc, docs/src/main/asciidoc/topics/StandaloneDistribution-ServerMigration.adoc
…orted subsystems removal, and introduces custom topic for server migration, from eap 6.4, user guides
JIRA:
=> CMTOOL-166: fix log messages in user guides

core/src/main/java/org/jboss/migration/core/MigrationFiles.java, core/src/main/java/org/jboss/migration/core/jboss/JBossServer.java, core/src/main/java/org/jboss/migration/core/jboss/JBossServerConfiguration.java, core/src/main/java/org/jboss/migration/core/logger/ServerMigrationLogger.java, core/src/test/java/org/jboss/migration/core/ts/jboss/ConfigFilesDiscoveryTest.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/management/impl/EmbeddedHostControllerConfiguration.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/management/impl/EmbeddedStandaloneServerConfiguration.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/DomainUpdate.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/InitializeTargetDirs.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/StandaloneServerUpdate.java
Issues:
* https://issues.jboss.org/projects/CMTOOL/issues/CMTOOL-174
* https://issues.jboss.org/projects/CMTOOL/issues/CMTOOL-175
=> CMTOOL-174 & 175 fixes for 1.0.x

pom.xml
Issue: https://issues.jboss.org/browse/CMTOOL-176
=> CMTOOL-176: updates WFCORE dependency version

cli/src/main/java/org/jboss/migration/cli/CommandLineConstants.java, cli/src/main/java/org/jboss/migration/cli/CommandLineOption.java, cli/src/main/java/org/jboss/migration/cli/CommandLineOptions.java, cli/src/main/java/org/jboss/migration/cli/CommandLineServerMigration.java
Issue: https://issues.jboss.org/browse/CMTOOL-177
=> CMTOOL-177: add support for deprecated interactive param

cli/src/main/java/org/jboss/migration/cli/CommandLineParser.java, cli/src/main/java/org/jboss/migration/cli/CommandLineServerMigration.java
Issue: https://issues.jboss.org/browse/CMTOOL-172
=> CMTOOL-172: adding parser with disabled concatenated options

eap7.2/src/main/java/org/jboss/migration/eap/EAPCDServerProvider7_2.java, eap7.2/src/main/resources/META-INF/services/org.jboss.migration.core.ServerProvider
JIRA: https://issues.jboss.org/browse/CMTOOL-189
=> CMTOOL-189: adding server provider for JBoss EAP CD 7.2 distributions

eap6.4-to-eap7.1/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_1ServerMigrationProvider.java, eap6.4-to-eap7.2/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_2ServerMigrationProvider.java, eap7.1/src/main/java/org/jboss/migration/eap/task/subsystem/web/EAP7_1MigrateWebSubsystem.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/web/MigrateWebSubsystem.java
JIRA: https://issues.jboss.org/browse/CMTOOL-179
=> CMTOOL-179 Master

eap6.4-to-eap7.1/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_1ServerMigrationProvider.java, eap7.1/src/main/java/org/jboss/migration/eap/task/subsystem/web/EAP7_1MigrateWebSubsystem.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/web/MigrateWebSubsystem.java
JIRA: https://issues.jboss.org/browse/CMTOOL-179
=> CMTOOL-179 1.0.x

eap6.4-to-eap7.0/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_0ServerMigrationProvider.java, eap6.4-to-eap7.0/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_0UpdateJGroupsSubsystem.java, eap6.4-to-eap7.1/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_1ServerMigrationProvider.java, eap6.4-to-eap7.1/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_1UpdateJGroupsSubsystem.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/jgroups/UpdateProtocols.java
JIRA: https://issues.jboss.org/projects/CMTOOL/issues/CMTOOL-188
=> CMTOOL-188 1.0.x

eap6.4-to-eap7.0/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_0UpdateJGroupsSubsystem.java, eap6.4-to-eap7.1/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_1UpdateJGroupsSubsystem.java, wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/jgroups/UpdateProtocols.java
JIRA: https://issues.jboss.org/browse/CMTOOL-188
Branch: 1.0.x
=> CMTOOL-188: fixes jgroups subsystem protocol stack updates

migrations/eap7.2/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_1ToEAP7_2ServerMigrationProvider.java
JIRA: https://issues.jboss.org/browse/CMTOOL-210
=> CMTOOL-210: adding host excludes setup on eap 7.1 to eap 7.2 migration

dist/feature-packs/eap7.2/src/main/resources/packages/migration.tool/content/bin/jboss-server-migration.bat, dist/feature-packs/eap7.2/src/main/resources/packages/migration.tool/content/bin/jboss-server-migration.sh, dist/standalone/src/main/resources/jboss-server-migration.bat, dist/standalone/src/main/resources/jboss-server-migration.sh, testsuite/integrated-server-migration-simple-interactive-test.sh, testsuite/integrated-server-migration-simple-test.sh, testsuite/integrated-server-migration-test.sh, testsuite/server-migration-simple-interactive-test.sh, testsuite/server-migration-simple-test.sh, testsuite/server-migration-test.sh
JIRA: https://issues.jboss.org/browse/CMTOOL-221
=> CMTOOL-221: add support for JDK 11

dist/standalone/src/main/resources/jboss-server-migration.sh
JIRA: https://issues.jboss.org/browse/CMTOOL-227
=> CMTOOL-227: fixes sh script

docs/user-guides/migrations/wildfly14.0/wildfly11.0/src/main/asciidoc/topics/WFLY11.0toWFLY14.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly14.0/wildfly12.0/src/main/asciidoc/topics/WFLY12.0toWFLY14.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly14.0/wildfly13.0/src/main/asciidoc/topics/WFLY13.0toWFLY14.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly15.0/wildfly11.0/src/main/asciidoc/topics/WFLY11.0toWFLY15.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly15.0/wildfly12.0/src/main/asciidoc/topics/WFLY12.0toWFLY15.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly15.0/wildfly13.0/src/main/asciidoc/topics/WFLY13.0toWFLY15.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, docs/user-guides/migrations/wildfly15.0/wildfly14.0/src/main/asciidoc/topics/WFLY14.0toWFLY15.0-ServerMigration-ManagedDomain-DomainConfiguration.adoc, migrations/wildfly14.0/wildfly10.0/src/main/java/org/jboss/migration/wfly/WildFly10_0ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly10.1/src/main/java/org/jboss/migration/wfly/WildFly10_1ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly11.0/src/main/java/org/jboss/migration/wfly/WildFly11_0ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly12.0/src/main/java/org/jboss/migration/wfly/WildFly12_0ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly13.0/src/main/java/org/jboss/migration/wfly/WildFly13_0ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly8.2/src/main/java/org/jboss/migration/wfly/WildFly8ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly14.0/wildfly9.0/src/main/java/org/jboss/migration/wfly/WildFly9ToWildFly14_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly10.0/src/main/java/org/jboss/migration/wfly/WildFly10_0ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly10.1/src/main/java/org/jboss/migration/wfly/WildFly10_1ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly11.0/src/main/java/org/jboss/migration/wfly/WildFly11_0ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly12.0/src/main/java/org/jboss/migration/wfly/WildFly12_0ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly13.0/src/main/java/org/jboss/migration/wfly/WildFly13_0ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly14.0/src/main/java/org/jboss/migration/wfly/WildFly14_0ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly8.2/src/main/java/org/jboss/migration/wfly/WildFly8ToWildFly15_0ServerMigrationProvider.java, migrations/wildfly15.0/wildfly9.0/src/main/java/org/jboss/migration/wfly/WildFly9ToWildFly15_0ServerMigrationProvider.java, servers/wildfly14.0/src/main/java/org/jboss/migration/wfly/task/hostexclude/WildFly14_0AddHostExcludes.java, servers/wildfly15.0/src/main/java/org/jboss/migration/wfly/task/hostexclude/WildFly15_0AddHostExcludes.java
JIRA: https://issues.jboss.org/browse/CMTOOL-231
=> CMTOOL-231: adds wfly 14 and 15 host excludes setup task

pom.xml, servers/eap7.3/pom.xml, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPCDServerProvider7_3.java, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPServer7_3.java, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPServerMigrationProvider7_3.java, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPServerProvider7_3.java, servers/eap7.3/src/main/resources/META-INF/services/org.jboss.migration.core.ServerProvider
JIRA: https://issues.jboss.org/browse/CMTOOL-237
=> CMTOOL-237: adds eap 7.3 server module

dist/standalone/pom.xml, migrations/eap7.3/eap6.4/pom.xml, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP7_3ServerMigrationProvider.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateEESubsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateEJB3Subsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateInfinispanSubsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateJGroupsSubsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateMessagingActiveMQSubsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateRemotingSubsystem.java, migrations/eap7.3/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_3UpdateUndertowSubsystem.java, migrations/eap7.3/eap6.4/src/main/resources/META-INF/services/org.jboss.migration.eap.EAPServerMigrationProvider7_3, pom.xml, servers/eap7.3/src/main/java/org/jboss/migration/eap/task/hostexclude/EAP7_3AddHostExcludes.java
JIRA: https://issues.jboss.org/browse/CMTOOL-238
=> CMTOOL-238: adds server migration from eap 6.4 to eap 7.3

dist/standalone/pom.xml, migrations/eap7.3/eap7.2/pom.xml, migrations/eap7.3/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_2ToEAP7_3ServerMigrationProvider.java, migrations/eap7.3/eap7.2/src/main/resources/META-INF/services/org.jboss.migration.eap.EAPServerMigrationProvider7_3, pom.xml
JIRA: https://issues.jboss.org/browse/CMTOOL-239
=> CMTOOL-239: adds server migration from eap 7.2 to eap 7.3

migrations/eap7.2/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_1ToEAP7_2ServerMigrationProvider.java, servers/eap7.2/src/main/java/org/jboss/migration/eap/task/hostexclude/EAP7_2AddHostExcludes.java
JIRA: https://issues.jboss.org/browse/CMTOOL-240
=> CMTOOL-240: updates eap 7.2 host excludes migration task

pom.xml
Issue: https://issues.jboss.org/browse/CMTOOL-246
=> [CMTOOL-246] upgrade WildFly Core to 8.0.0.Final

pom.xml
Issue: https://issues.jboss.org/browse/CMTOOL-252
=> [CMTOOL-252] Upgrade WildFly Core to 9.0.1.Final

migrations/wildfly17.0/wildfly10.0/src/main/java/org/jboss/migration/wfly/WildFly10_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly10.1/src/main/java/org/jboss/migration/wfly/WildFly10_1ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly11.0/src/main/java/org/jboss/migration/wfly/WildFly11_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly12.0/src/main/java/org/jboss/migration/wfly/WildFly12_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly13.0/src/main/java/org/jboss/migration/wfly/WildFly13_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly14.0/src/main/java/org/jboss/migration/wfly/WildFly14_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly15.0/src/main/java/org/jboss/migration/wfly/WildFly15_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly16.0/src/main/java/org/jboss/migration/wfly/WildFly16_0ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly8.2/src/main/java/org/jboss/migration/wfly/WildFly8ToWildFly17_0ServerMigrationProvider.java, migrations/wildfly17.0/wildfly9.0/src/main/java/org/jboss/migration/wfly/WildFly9ToWildFly17_0ServerMigrationProvider.java, servers/wildfly17.0/src/main/java/org/jboss/migration/wfly/task/hostexclude/WildFly17_0AddHostExcludes.java
Issue: https://issues.jboss.org/browse/CMTOOL-258
=> [CMTOOL-258] wfly 17 host-excludes setup

servers/eap7.3/pom.xml, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPServer7_3.java, servers/eap7.3/src/main/java/org/jboss/migration/eap/task/hostexclude/EAP7_3AddHostExcludes.java
Issue: https://issues.jboss.org/browse/CMTOOL-253
=> [CMTOOL-253] update JBoss EAP 7.3 Host-Excludes Setup

dist/standalone/pom.xml, pom.xml, servers/wildfly19.0/pom.xml, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0Server.java, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ServerMigrationProvider.java, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ServerProvider.java, servers/wildfly19.0/src/main/resources/META-INF/services/org.jboss.migration.core.ServerProvider
Issue: https://issues.redhat.com/browse/CMTOOL-263
=> [CMTOOL-263] adds WildFly 19.0 Server

core/src/main/java/org/jboss/migration/core/jboss/JBossExtensionNames.java, core/src/main/java/org/jboss/migration/core/jboss/JBossExtensions.java, core/src/main/java/org/jboss/migration/core/jboss/JBossSubsystemNames.java, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0Server.java
Issue: https://issues.redhat.com/browse/CMTOOL-266
=> [CMTOOL-266] add Microprofile JWT Smallrye Extension

migrations/wildfly19.0/wildfly10.0/src/main/java/org/jboss/migration/wfly/WildFly10_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly10.1/src/main/java/org/jboss/migration/wfly/WildFly10_1ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly11.0/src/main/java/org/jboss/migration/wfly/WildFly11_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly12.0/src/main/java/org/jboss/migration/wfly/WildFly12_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly13.0/src/main/java/org/jboss/migration/wfly/WildFly13_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly14.0/src/main/java/org/jboss/migration/wfly/WildFly14_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly15.0/src/main/java/org/jboss/migration/wfly/WildFly15_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly16.0/src/main/java/org/jboss/migration/wfly/WildFly16_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly17.0/src/main/java/org/jboss/migration/wfly/WildFly17_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly18.0/src/main/java/org/jboss/migration/wfly/WildFly18_0ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly8.2/src/main/java/org/jboss/migration/wfly/WildFly8ToWildFly19_0ServerMigrationProvider.java, migrations/wildfly19.0/wildfly9.0/src/main/java/org/jboss/migration/wfly/WildFly9ToWildFly19_0ServerMigrationProvider.java, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/task/hostexclude/WildFly19_0AddHostExcludes.java
Issue: https://issues.redhat.com/browse/CMTOOL-267
=> [CMTOOL-267] adds WFLY 19 host-excludes setup

servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/dist/full/WildFlyFullServerProvider10_0.java, servers/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ServerProvider.java
Issue: https://issues.redhat.com/browse/CMTOOL-272
=> [CMTOOL-272] fixes wfly 19 server provider

servers/wildfly11.0/src/main/java/org/jboss/migration/wfly11/task/subsystem/elytron/AddElytronSubsystemConfig.java
Issue: https://issues.redhat.com/browse/CMTOOL-277
=> [CMTOOL-277] fix mechanism realm-name in AddElytronSubsystemConfig

servers/eap7.0/src/main/java/org/jboss/migration/eap/EAPServer7_0.java, servers/eap7.1/src/main/java/org/jboss/migration/eap/EAPServer7_1.java, servers/eap7.2/src/main/java/org/jboss/migration/eap/EAPServer7_2.java, servers/eap7.3/src/main/java/org/jboss/migration/eap/EAPServer7_3.java
Issue: https://issues.redhat.com/browse/CMTOOL-279
=> [CMTOOL-279] EAP servers should not extend a concrete WildFly server

pom.xml
Issue: https://issues.redhat.com/browse/CMTOOL-282
=> [CMTOOL-282] Upgrade WFLY Core to 12.0.1.Final

core/src/main/java/org/jboss/migration/core/util/xml/XMLFileFilter.java, core/src/main/java/org/jboss/migration/core/util/xml/XMLFiles.java, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/update/RemoveUnsupportedExtensions.java
Issue: https://issues.redhat.com/browse/CMTOOL-287
=> [CMTOOL-287] don't remove unsupported extensions from host-excludes

core/src/main/java/org/jboss/migration/core/jboss/JBossServer.java
Issue: https://issues.redhat.com/browse/CMTOOL-288
=> [CMTOOL-288] multiple module layers support

dist/standalone/src/main/resources/configuration/environment.properties, docs/user-guides/migrations/eap7.1/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.1-ServerMigration-ServerConfiguration-Subsystem-Update-ee.adoc, docs/user-guides/migrations/eap7.1/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.1-ServerMigration-ServerConfiguration-Subsystem-Update-undertow.adoc, docs/user-guides/migrations/eap7.2/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.2-ServerMigration-ServerConfiguration-Subsystem-Update-ee.adoc, docs/user-guides/migrations/eap7.2/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.2-ServerMigration-ServerConfiguration-Subsystem-Update-undertow.adoc, docs/user-guides/migrations/eap7.3/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.3-ServerMigration-ServerConfiguration-Subsystem-Update-ee.adoc, docs/user-guides/migrations/eap7.3/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.3-ServerMigration-ServerConfiguration-Subsystem-Update-undertow.adoc, docs/user-guides/migrations/eap7.4/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.4-ServerMigration-ServerConfiguration-Subsystem-Update-ee.adoc, docs/user-guides/migrations/eap7.4/eap6.4/src/main/asciidoc/topics/EAP6.4toEAP7.4-ServerMigration-ServerConfiguration-Subsystem-Update-undertow.adoc, docs/user-guides/migrations/includes/src/main/resources/topics/ServerMigration-ServerConfiguration-Subsystem-Add-security-manager.adoc, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/ee/AddDefaultBindingsConfig.java, testsuite/before/src/deployments/helloworldX/pom.xml
Issue: https://issues.redhat.com/browse/CMTOOL-304
=> [CMTOOL-304] move to Jakarta EE

dist/standalone/src/main/resources/jboss-server-migration.ps1
https://issues.redhat.com/browse/CMTOOL-308
https://issues.redhat.com/browse/JBEAP-12319
=> [JBEAP-12319] Adding .ps1 script version.

migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP7_3ToEAPXP8_0ServerMigrationProvider.java, servers/eap8.0/src/main/java/org/jboss/migration/eap/task/subsystem/metrics/EAP8_0AddMetricsSubsystem.java
https://issues.redhat.com/browse/CMTOOL-331
=> [CMTOOL-331] migrate jboss metrics prefix to EAP 8.0

migrations/eap7.4/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/tasks/EAP6_4ToEAP7_4UpdateInfinispanSubsystem.java, migrations/eap7.4/eap7.0/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_0ToEAP7_4UpdateInfinispanSubsystem.java, migrations/eap7.4/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_1ToEAP7_4ServerMigrationProvider.java, migrations/eap7.4/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_2ToEAP7_4ServerMigrationProvider.java, migrations/eap7.4/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP7_4ServerMigrationProvider.java, migrations/eap8.0/eap6.4/src/main/java/org/jboss/migration/eap6/to/eap7/EAP6_4ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.0/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_0ToEAP8_0UpdateInfinispanSubsystem.java, migrations/eap8.0/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_1ToEAP8_0UpdateInfinispanSubsystem.java, migrations/eap8.0/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_2ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP8_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly14.0/src/main/java/org/jboss/migration/wfly/WildFly14_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly15.0/src/main/java/org/jboss/migration/wfly/WildFly15_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly16.0/src/main/java/org/jboss/migration/wfly/WildFly16_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly17.0/src/main/java/org/jboss/migration/wfly/WildFly17_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly18.0/src/main/java/org/jboss/migration/wfly/WildFly18_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly20.0/src/main/java/org/jboss/migration/wfly/WildFly20_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly21.0/src/main/java/org/jboss/migration/wfly/WildFly21_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly26.0/wildfly22.0/src/main/java/org/jboss/migration/wfly/WildFly22_0ToWildFly26_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly18.0/src/main/java/org/jboss/migration/wfly/WildFly18_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly20.0/src/main/java/org/jboss/migration/wfly/WildFly20_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly21.0/src/main/java/org/jboss/migration/wfly/WildFly21_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly22.0/src/main/java/org/jboss/migration/wfly/WildFly22_0ToWildFly27_0ServerMigrationProvider.java, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/infinispan/FixHibernateCacheModuleName.java, servers/wildfly22.0/src/main/java/org/jboss/migration/wfly/task/subsystem/infinispan/WildFly22_0FixHibernateCacheModuleName.java, servers/wildfly22.0/src/main/java/org/jboss/migration/wfly/task/update/WildFly22_0UpdateInfinispanSubsystem.java
https://issues.redhat.com/browse/CMTOOL-337
=> [JBEAP-24377] new attribute modules in hibernate cache-container

migrations/eap8.0/eap7.0/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_0ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_1ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_2ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.4/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_4ToEAP8_0ServerMigrationProvider.java
Issue: https://issues.redhat.com/browse/CMTOOL-335
=> [CMTOOL-335] add deployments migration task

.github/workflows/ci.yml
Issue: https://issues.redhat.com/browse/CMTOOL-342
=> [CMTOOL-342] Adds GitHub CI Actions

pom.xml
Issue: https://issues.redhat.com/browse/CMTOOL-343
=> [CMTOOL-343] Fixes junit dependency management

core/src/main/java/org/jboss/migration/core/jboss/JBossExtensionNames.java, core/src/main/java/org/jboss/migration/core/jboss/JBossExtensions.java, core/src/main/java/org/jboss/migration/core/jboss/JBossServer.java, core/src/main/java/org/jboss/migration/core/jboss/JBossSubsystemNames.java, migrations/eap8.0/eap7.0/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_0ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_1ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_2ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP7_3ToEAPXP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.4/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_4ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.4/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP7_4ToEAPXP8_0ServerMigrationProvider.java, migrations/eap8.0/eap8.0/src/main/java/org/jboss/migration/eap7/to/eap7/EAP8_0ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap8.0/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP8_0ToEAPXP8_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly18.0/src/main/java/org/jboss/migration/wfly/WildFly18_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly19.0/src/main/java/org/jboss/migration/wfly/WildFly19_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly20.0/src/main/java/org/jboss/migration/wfly/WildFly20_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly21.0/src/main/java/org/jboss/migration/wfly/WildFly21_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly22.0/src/main/java/org/jboss/migration/wfly/WildFly22_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly23.0/src/main/java/org/jboss/migration/wfly/WildFly23_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly24.0/src/main/java/org/jboss/migration/wfly/WildFly24_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly25.0/src/main/java/org/jboss/migration/wfly/WildFly25_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly26.0/src/main/java/org/jboss/migration/wfly/WildFly26_0ToWildFly27_0ServerMigrationProvider.java, migrations/wildfly27.0/wildfly27.0/src/main/java/org/jboss/migration/wfly/WildFly27_0ToWildFly27_0ServerMigrationProvider.java, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/dist/full/WildFlyFullServer10_0.java, servers/wildfly27.0/src/main/java/org/jboss/migration/wfly/task/subsystem/keycloak/MigrateKeycloakSubsystem.java
Issues:
https://issues.redhat.com/browse/CMTOOL-347
https://issues.redhat.com/browse/CMTOOL-345
=> [CMTOOL-347]  and [CMTOOL-345]

migrations/eap8.0/eap7.1/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_1ToEAP8_0UpdateJGroupsSubsystem.java, migrations/eap8.0/eap7.2/src/main/java/org/jboss/migration/eap7/to/eap8/EAP7_2ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_3ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.3/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP7_3ToEAPXP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.4/src/main/java/org/jboss/migration/eap7/to/eap7/EAP7_4ToEAP8_0ServerMigrationProvider.java, migrations/eap8.0/eap7.4/src/main/java/org/jboss/migration/eap7/to/eap7/EAPXP7_4ToEAPXP8_0ServerMigrationProvider.java, servers/eap7.2/src/main/java/org/jboss/migration/eap/task/subsystem/jgroups/EAP7_2AddFDSockProtocolOperation.java, servers/eap7.2/src/main/java/org/jboss/migration/eap/task/subsystem/jgroups/EAP7_2AddPingMPingProtocolOperation.java, servers/eap7.2/src/main/java/org/jboss/migration/eap/task/subsystem/jgroups/EAP7_2ToEAP8_0UpdateJGroupsSubsystem.java, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/subsystem/jgroups/UpdateProtocols.java
Issue: https://issues.redhat.com/browse/CMTOOL-338
=> [CMTOOL-338] added migration of jgroups protocols to EAP8 defaults

core/src/main/java/org/jboss/migration/core/jboss/ManifestProductInfo.java, servers/eap8.0/src/main/java/org/jboss/migration/eap/EAPServerProvider8_0.java
Issue: https://issues.redhat.com/browse/CMTOOL-358
=> [CMTOOL-358] fixes EAP 8.0 GA server detection

pom.xml
Issue: https://issues.redhat.com/browse/CMTOOL-324
=> [CMTOOL-324] Add JBoss and Red Hat repositories

servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/management/subsystem/AddSubsystemResourceSubtaskBuilder.java
Issue: https://issues.redhat.com/browse/CMTOOL-368
=> [CMTOOL-368] only adds subsystem configs to leaf profiles

servers/wildfly26.0/src/main/java/org/jboss/migration/wfly/task/security/LegacySecurityConfiguration.java, servers/wildfly27.0/src/main/java/org/jboss/migration/wfly/task/subsystem/keycloak/MigrateKeycloakSubsystem.java
Issue: https://issues.redhat.com/browse/CMTOOL-364
=> [CMTOOL-364] fixed migration of keycloak sasl authentication factory

core/src/main/java/org/jboss/migration/core/jboss/JBossServer.java, core/src/main/java/org/jboss/migration/core/jboss/ModulesMigrationTask.java, testsuite/server-migration-simple-test-raw.sh
Issue: https://issues.redhat.com/browse/CMTOOL-372
=> [CMTOOL-372] skips migration of internal modules

servers/wildfly26.0/src/main/java/org/jboss/migration/wfly/task/security/MigrateLegacySecurityDomainsToElytron.java
Issue: https://issues.redhat.com/browse/CMTOOL-352
=> [CMTOOL-352] migrated legacy security domains on datasources and resource-adapters to elytron

servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/paths/ElytronSubsystemSecretKeyCredentialStorePathsMigration.java, servers/wildfly10.0/src/main/java/org/jboss/migration/wfly10/config/task/paths/MigrateReferencedPaths.java, servers/wildfly26.0/src/main/java/org/jboss/migration/wfly/task/paths/WildFly26_0MigrateReferencedPaths.java
Issue: https://issues.redhat.com/browse/CMTOOL-382
=> [CMTOOL-382] migrate secret-key-credential-store paths

core/src/main/java/org/jboss/migration/core/jboss/JBossExtensions.java
Issue: https://issues.redhat.com/browse/CMTOOL-384
=> [CMTOOL-384] Fixes namespaces for distributable-* subsystems

dist/standalone/src/main/resources/jboss-server-migration.bat, dist/standalone/src/main/resources/jboss-server-migration.ps1
Issue: https://issues.redhat.com/browse/CMTOOL-388
=> CMTOOL-388 Update bat script to distinguish between JVM args and tool args
